### ISSUE TITLE
Using  Adafruit Feather RP2040 with USB Type A Host for this project?

### ISSUE THREAD

**Issue by DenshaMan** [sonik-br/ddgo_usb_adapt#2]
Hi there,
I just discovered your ddgo_us_adapt github and am thrilled, as I've been looking for a solution to connect my DDG PS2 controller TCPP-20009 to PC (and Titan Two USB converter) for YEARS now!! As I'm not able to solder, I was wondering if the following pre-built RP2040 would also work and if not, is there a way in which your code could be changed in order to make it work?

Adafruit Feather RP2040 with USB Type A Host (https://www.adafruit.com/product/5723)

I don't know anything about Pi or Arduino programming :(

I really hope you read this and would be able to help! Thank you so much!!

**Comment by sonik-br** [comment]
Hey, do you still want to use the adapter with a Adafruit Feather?
No idea why I did not see your post before.
